-- Generated by tools/build-seed.mjs from data/stops.json v2.0.0
-- 42 menu items across 14 stops. Do not edit by hand.

insert into public.stop_items (key, stop_id, item_id, item_type) values
  ('ovenbird-rotunda:chocolate-chirp', 'ovenbird-rotunda', 'chocolate-chirp', 'cookie'),
  ('ovenbird-rotunda:morning-bun', 'ovenbird-rotunda', 'morning-bun', 'other'),
  ('ovenbird-rotunda:sourdough-loaf', 'ovenbird-rotunda', 'sourdough-loaf', 'other'),
  ('harmony-bakery:cc-cookie', 'harmony-bakery', 'cc-cookie', 'cookie'),
  ('harmony-bakery:spinach-pie', 'harmony-bakery', 'spinach-pie', 'other'),
  ('harmony-bakery:slice-pizza', 'harmony-bakery', 'slice-pizza', 'other'),
  ('common-ground:cc-cookie', 'common-ground', 'cc-cookie', 'cookie'),
  ('common-ground:muffin', 'common-ground', 'muffin', 'other'),
  ('common-ground:drip-coffee', 'common-ground', 'drip-coffee', 'other'),
  ('la-maison-dear-leon:cc-cookie', 'la-maison-dear-leon', 'cc-cookie', 'cookie'),
  ('la-maison-dear-leon:smores-cookie', 'la-maison-dear-leon', 'smores-cookie', 'cookie'),
  ('la-maison-dear-leon:latte', 'la-maison-dear-leon', 'latte', 'other'),
  ('insomnia-charles-village:classic-cc', 'insomnia-charles-village', 'classic-cc', 'cookie'),
  ('insomnia-charles-village:deluxe-cc', 'insomnia-charles-village', 'deluxe-cc', 'cookie'),
  ('insomnia-charles-village:double-chocolate', 'insomnia-charles-village', 'double-chocolate', 'cookie'),
  ('aunt-kellys:cc-cookie', 'aunt-kellys', 'cc-cookie', 'cookie'),
  ('aunt-kellys:butter-crunch', 'aunt-kellys', 'butter-crunch', 'cookie'),
  ('aunt-kellys:butter-pecan', 'aunt-kellys', 'butter-pecan', 'cookie'),
  ('patisserie-poupon:cc-cookie', 'patisserie-poupon', 'cc-cookie', 'cookie'),
  ('patisserie-poupon:canele', 'patisserie-poupon', 'canele', 'other'),
  ('patisserie-poupon:pain-au-chocolat', 'patisserie-poupon', 'pain-au-chocolat', 'other'),
  ('ovenbird-little-italy:chocolate-chirp', 'ovenbird-little-italy', 'chocolate-chirp', 'cookie'),
  ('ovenbird-little-italy:focaccia', 'ovenbird-little-italy', 'focaccia', 'other'),
  ('ovenbird-little-italy:sourdough-loaf', 'ovenbird-little-italy', 'sourdough-loaf', 'other'),
  ('kneads-bakeshop:cc-chunk', 'kneads-bakeshop', 'cc-chunk', 'cookie'),
  ('kneads-bakeshop:sprinkledoodle', 'kneads-bakeshop', 'sprinkledoodle', 'cookie'),
  ('kneads-bakeshop:oatmeal-raisin', 'kneads-bakeshop', 'oatmeal-raisin', 'cookie'),
  ('pitango-bakery:cc-cookie', 'pitango-bakery', 'cc-cookie', 'cookie'),
  ('pitango-bakery:cornetto', 'pitango-bakery', 'cornetto', 'other'),
  ('pitango-bakery:espresso', 'pitango-bakery', 'espresso', 'other'),
  ('sacre-sucre:cc-cookie', 'sacre-sucre', 'cc-cookie', 'cookie'),
  ('sacre-sucre:macaron', 'sacre-sucre', 'macaron', 'other'),
  ('sacre-sucre:eclair', 'sacre-sucre', 'eclair', 'other'),
  ('cafe-dear-leon:cc-cookie', 'cafe-dear-leon', 'cc-cookie', 'cookie'),
  ('cafe-dear-leon:smores-cookie', 'cafe-dear-leon', 'smores-cookie', 'cookie'),
  ('cafe-dear-leon:cortado', 'cafe-dear-leon', 'cortado', 'other'),
  ('ovenbird-highlandtown:chocolate-chirp', 'ovenbird-highlandtown', 'chocolate-chirp', 'cookie'),
  ('ovenbird-highlandtown:morning-bun', 'ovenbird-highlandtown', 'morning-bun', 'other'),
  ('ovenbird-highlandtown:sourdough-loaf', 'ovenbird-highlandtown', 'sourdough-loaf', 'other'),
  ('zoes-just-dezzerts:cc-cookie', 'zoes-just-dezzerts', 'cc-cookie', 'cookie'),
  ('zoes-just-dezzerts:cupcake', 'zoes-just-dezzerts', 'cupcake', 'other'),
  ('zoes-just-dezzerts:tart', 'zoes-just-dezzerts', 'tart', 'other')
on conflict (key) do update
  set stop_id = excluded.stop_id,
      item_id = excluded.item_id,
      item_type = excluded.item_type;

-- Menu items that no longer exist in stops.json are left in place on purpose.
-- Deleting them would cascade and destroy the scores that reference them.
