/*
 * Generates db/seed.sql from data/stops.json.
 *
 * The database keeps a reference table of every stop and menu item so a score
 * can never point at something that does not exist. Rerun this whenever
 * stops.json changes:
 *
 *   node tools/build-seed.mjs
 *
 * then paste db/seed.sql into the Supabase SQL editor.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const data = JSON.parse(readFileSync(join(root, 'data', 'stops.json'), 'utf8'));

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;

const rows = [];
for (const stop of data.stops) {
  for (const item of stop.menu) {
    rows.push(`  (${q(`${stop.id}:${item.id}`)}, ${q(stop.id)}, ${q(item.id)}, ${q(item.type)})`);
  }
}

const sql = `-- Generated by tools/build-seed.mjs from data/stops.json v${data.version}
-- ${rows.length} menu items across ${data.stops.length} stops. Do not edit by hand.

insert into public.stop_items (key, stop_id, item_id, item_type) values
${rows.join(',\n')}
on conflict (key) do update
  set stop_id = excluded.stop_id,
      item_id = excluded.item_id,
      item_type = excluded.item_type;

-- Menu items that no longer exist in stops.json are left in place on purpose.
-- Deleting them would cascade and destroy the scores that reference them.
`;

writeFileSync(join(root, 'db', 'seed.sql'), sql);
console.log(`db/seed.sql written: ${rows.length} items, ${data.stops.length} stops.`);
